// <auto-generated />
namespace UserApplication2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class passuser_validator : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(passuser_validator));
        
        string IMigrationMetadata.Id
        {
            get { return "201905031809109_pass-user_validator"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
